### ISSUE TITLE
search

### ISSUE THREAD

**Issue by auburnsummer** [auburnsummer/orchard#13]
couple of different options, from easiest to hardest to implement:

 - [meilisearch](https://www.meilisearch.com/)'
   - apparently works ootb
 - postgresql full text search
   - easiest for deployment, but apparently not great at non-english texts
 - elasticsearch

**Comment by auburnsummer** [comment]
meili is promising

![Screen Recording 2020-07-01 at 2 47 35 pm](https://user-images.githubusercontent.com/37142182/86204205-3c604d00-bbaa-11ea-87ee-1095b7b6333d.gif)

**Comment by DPS2004** [comment]
George Clooney, my favorite Rhythm Doctor custom level
