### ISSUE TITLE
Letting level creators know that people are playing their levels

### ISSUE THREAD

**Issue by auburnsummer** [auburnsummer/orchard#5]
Sometimes uploading a level can feel like throwing your level into the `v o i d` due to lack of feedback mechanisms.

If you're lucky, you'll get pinged a few times on Discord as people play your level. but this is happening less and less.

This issue is for discussing ways we can let people know that people are playing their levels.

 - level comment system?
 - download count on levels?
 - maybe a Nintendo-esque system where you can put "yeah!" on levels

**Comment by DPS2004** [comment]
i think a "yeah" system would help

**Comment by auburnsummer** [comment]
#pharmacy discussion 3/04/2020: https://discordapp.com/channels/296802696243970049/419900766279696384/695342714253869117
